/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccountSecurityRouteImport } from './routes/account/security'
import { Route as LoginTwoFactorRouteImport } from './routes/login/two-factor'
import { Route as VaultDcMcfarlaneRouteImport } from './routes/vault/dc-mcfarlane'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ShareCollectionTokenRouteImport } from './routes/share/collection.$token'
import { Route as ShareItemTokenRouteImport } from './routes/share/item.$token'
import { Route as ShareVaultTokenRouteImport } from './routes/share/vault.$token'
import { Route as ShareWishlistTokenRouteImport } from './routes/share/wishlist.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/account/security',
  path: '/account/security',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginTwoFactorRoute = LoginTwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => LoginRoute,
} as any)
const VaultDcMcfarlaneRoute = VaultDcMcfarlaneRouteImport.update({
  id: '/vault/dc-mcfarlane',
  path: '/vault/dc-mcfarlane',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareCollectionTokenRoute = ShareCollectionTokenRouteImport.update({
  id: '/share/collection/$token',
  path: '/share/collection/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareItemTokenRoute = ShareItemTokenRouteImport.update({
  id: '/share/item/$token',
  path: '/share/item/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareVaultTokenRoute = ShareVaultTokenRouteImport.update({
  id: '/share/vault/$token',
  path: '/share/vault/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareWishlistTokenRoute = ShareWishlistTokenRouteImport.update({
  id: '/share/wishlist/$token',
  path: '/share/wishlist/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/account/security': typeof AccountSecurityRoute
  '/login/two-factor': typeof LoginTwoFactorRoute
  '/vault/dc-mcfarlane': typeof VaultDcMcfarlaneRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/share/collection/$token': typeof ShareCollectionTokenRoute
  '/share/item/$token': typeof ShareItemTokenRoute
  '/share/vault/$token': typeof ShareVaultTokenRoute
  '/share/wishlist/$token': typeof ShareWishlistTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/account/security': typeof AccountSecurityRoute
  '/login/two-factor': typeof LoginTwoFactorRoute
  '/vault/dc-mcfarlane': typeof VaultDcMcfarlaneRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/share/collection/$token': typeof ShareCollectionTokenRoute
  '/share/item/$token': typeof ShareItemTokenRoute
  '/share/vault/$token': typeof ShareVaultTokenRoute
  '/share/wishlist/$token': typeof ShareWishlistTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/account/security': typeof AccountSecurityRoute
  '/login/two-factor': typeof LoginTwoFactorRoute
  '/vault/dc-mcfarlane': typeof VaultDcMcfarlaneRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/share/collection/$token': typeof ShareCollectionTokenRoute
  '/share/item/$token': typeof ShareItemTokenRoute
  '/share/vault/$token': typeof ShareVaultTokenRoute
  '/share/wishlist/$token': typeof ShareWishlistTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account/security'
    | '/login/two-factor'
    | '/vault/dc-mcfarlane'
    | '/api/auth/$'
    | '/share/collection/$token'
    | '/share/item/$token'
    | '/share/vault/$token'
    | '/share/wishlist/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/account/security'
    | '/login/two-factor'
    | '/vault/dc-mcfarlane'
    | '/api/auth/$'
    | '/share/collection/$token'
    | '/share/item/$token'
    | '/share/vault/$token'
    | '/share/wishlist/$token'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/account/security'
    | '/login/two-factor'
    | '/vault/dc-mcfarlane'
    | '/api/auth/$'
    | '/share/collection/$token'
    | '/share/item/$token'
    | '/share/vault/$token'
    | '/share/wishlist/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRouteWithChildren
  AccountSecurityRoute: typeof AccountSecurityRoute
  VaultDcMcfarlaneRoute: typeof VaultDcMcfarlaneRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ShareCollectionTokenRoute: typeof ShareCollectionTokenRoute
  ShareItemTokenRoute: typeof ShareItemTokenRoute
  ShareVaultTokenRoute: typeof ShareVaultTokenRoute
  ShareWishlistTokenRoute: typeof ShareWishlistTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/security': {
      id: '/account/security'
      path: '/account/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/two-factor': {
      id: '/login/two-factor'
      path: '/two-factor'
      fullPath: '/login/two-factor'
      preLoaderRoute: typeof LoginTwoFactorRouteImport
      parentRoute: typeof LoginRoute
    }
    '/vault/dc-mcfarlane': {
      id: '/vault/dc-mcfarlane'
      path: '/vault/dc-mcfarlane'
      fullPath: '/vault/dc-mcfarlane'
      preLoaderRoute: typeof VaultDcMcfarlaneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/collection/$token': {
      id: '/share/collection/$token'
      path: '/share/collection/$token'
      fullPath: '/share/collection/$token'
      preLoaderRoute: typeof ShareCollectionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/item/$token': {
      id: '/share/item/$token'
      path: '/share/item/$token'
      fullPath: '/share/item/$token'
      preLoaderRoute: typeof ShareItemTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/vault/$token': {
      id: '/share/vault/$token'
      path: '/share/vault/$token'
      fullPath: '/share/vault/$token'
      preLoaderRoute: typeof ShareVaultTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/wishlist/$token': {
      id: '/share/wishlist/$token'
      path: '/share/wishlist/$token'
      fullPath: '/share/wishlist/$token'
      preLoaderRoute: typeof ShareWishlistTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LoginRouteChildren {
  LoginTwoFactorRoute: typeof LoginTwoFactorRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginTwoFactorRoute: LoginTwoFactorRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRouteWithChildren,
  AccountSecurityRoute: AccountSecurityRoute,
  VaultDcMcfarlaneRoute: VaultDcMcfarlaneRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ShareCollectionTokenRoute: ShareCollectionTokenRoute,
  ShareItemTokenRoute: ShareItemTokenRoute,
  ShareVaultTokenRoute: ShareVaultTokenRoute,
  ShareWishlistTokenRoute: ShareWishlistTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
